In [1]:
# 1. जरूरी लाइब्रेरीज इंस्टॉल और इम्पोर्ट करें
!pip install -q transformers datasets accelerate torch
import torch
import gc
from datasets import load_dataset
from transformers import (
    AutoTokenizer, 
    AutoConfig, 
    AutoModelForCausalLM, 
    Trainer, 
    TrainingArguments, 
    DataCollatorForLanguageModeling
)

print("लॉन्चिंग ZENO AI: स्टेप-बाय-स्टेप (Curriculum Learning) ट्रेनिंग...")

# टोकनाइज़र और Data Collator एक ही बार सेट करेंगे
tokenizer = AutoTokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=128)

# ==========================================
# स्टेज 1: हिंदी-इंग्लिश वोकैबुलरी (Language Foundation)
# ==========================================
print("\n--- स्टेज 1 शुरू: हिंदी-इंग्लिश वोकैबुलरी ---")
ds_hindi = load_dataset("cfilt/iitb-english-hindi", split="train[:1%]")
def format_hindi(example):
    translation = example.get("translation", {})
    return {"text": f"English: {translation.get('en', '')}\nHindi: {translation.get('hi', '')}"}
ds_hindi = ds_hindi.map(format_hindi, remove_columns=ds_hindi.column_names)
tokenized_stage1 = ds_hindi.map(tokenize_function, batched=True)

# बिल्कुल खाली दिमाग (Scratch) से शुरू कर रहे हैं
config = AutoConfig.from_pretrained("gpt2") 
model = AutoModelForCausalLM.from_config(config) 

args_stage1 = TrainingArguments(
    output_dir="/kaggle/working/temp_stage1",
    num_train_epochs=1, per_device_train_batch_size=8,
    save_steps=500, fp16=torch.cuda.is_available(), report_to="none"
)

trainer1 = Trainer(model=model, args=args_stage1, train_dataset=tokenized_stage1, data_collator=data_collator)
trainer1.train()

# स्टेज 1 का मॉडल सेव करें
print("स्टेज 1 पूरा हुआ! मॉडल 'zeno_step1' में सेव हो रहा है...")
model.save_pretrained("/kaggle/working/zeno_step1")
tokenizer.save_pretrained("/kaggle/working/zeno_step1")

# मेमोरी (RAM/GPU) साफ करें ताकि Colab/Kaggle क्रैश न हो
del trainer1, model, ds_hindi, tokenized_stage1
torch.cuda.empty_cache()
gc.collect()

# ==========================================
# स्टेज 2: प्रोग्रामिंग और कोडिंग (Technical Skills)
# ==========================================
print("\n--- स्टेज 2 शुरू: प्रोग्रामिंग ट्रेनिंग ---")
ds_code = load_dataset("flytech/python-codes-25k", split="train[:2%]")
def format_code(example):
    return {"text": f"Task: {example.get('instruction', '')}\nSolution: {example.get('output', '')}"}
ds_code = ds_code.map(format_code, remove_columns=ds_code.column_names)
tokenized_stage2 = ds_code.map(tokenize_function, batched=True)

# ध्यान दें: यहाँ हम 'zeno_step1' से मॉडल लोड कर रहे हैं (ताकि वो पुरानी बातें न भूले)
model = AutoModelForCausalLM.from_pretrained("/kaggle/working/zeno_step1")

args_stage2 = TrainingArguments(
    output_dir="/kaggle/working/temp_stage2",
    num_train_epochs=1, per_device_train_batch_size=8,
    save_steps=500, fp16=torch.cuda.is_available(), report_to="none"
)

trainer2 = Trainer(model=model, args=args_stage2, train_dataset=tokenized_stage2, data_collator=data_collator)
trainer2.train()

print("स्टेज 2 पूरा हुआ! मॉडल 'zeno_step2' में सेव हो रहा है...")
model.save_pretrained("/kaggle/working/zeno_step2")

# मेमोरी फिर से साफ करें
del trainer2, model, ds_code, tokenized_stage2
torch.cuda.empty_cache()
gc.collect()

# ==========================================
# स्टेज 3: राइटिंग और स्टोरीटेलिंग (Creative Skills)
# ==========================================
print("\n--- स्टेज 3 शुरू: राइटिंग और स्टोरीटेलिंग ---")
ds_writing = load_dataset("roneneldan/TinyStories", split="train[:2%]")
tokenized_stage3 = ds_writing.map(tokenize_function, batched=True)

# अब हम 'zeno_step2' को लोड करेंगे, जिसमें भाषा और कोडिंग दोनों का ज्ञान है
model = AutoModelForCausalLM.from_pretrained("/kaggle/working/zeno_step2")

args_stage3 = TrainingArguments(
    output_dir="/kaggle/working/temp_stage3",
    num_train_epochs=1, per_device_train_batch_size=8,
    save_steps=500, fp16=torch.cuda.is_available(), report_to="none"
)

trainer3 = Trainer(model=model, args=args_stage3, train_dataset=tokenized_stage3, data_collator=data_collator)
trainer3.train()

print("स्टेज 3 पूरा हुआ! फाइनल ZENO AI तैयार हो रहा है...")
model.save_pretrained("/kaggle/working/zeno_final_model")
tokenizer.save_pretrained("/kaggle/working/zeno_final_model")

print("🎉 बधाई हो! आपका स्टेप-बाय-स्टेप ट्रेन किया हुआ ZENO AI '/kaggle/working/zeno_final_model' में सेव हो गया है।")

लॉन्चिंग ZENO AI: स्टेप-बाय-स्टेप (Curriculum Learning) ट्रेनिंग...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

--- स्टेज 1 शुरू: हिंदी-इंग्लिश वोकैबुलरी ---

README.md: 0.00B [00:00, ?B/s]

dataset_infos.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/190M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/85.7k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/500k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1659083 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/520 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2507 [00:00<?, ? examples/s]

Map:   0%|          | 0/16591 [00:00<?, ? examples/s]

Map:   0%|          | 0/16591 [00:00<?, ? examples/s]

`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.
`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

स्टेज 1 पूरा हुआ! मॉडल 'zeno_step1' में सेव हो रहा है...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

--- स्टेज 2 शुरू: प्रोग्रामिंग ट्रेनिंग ---

README.md: 0.00B [00:00, ?B/s]

python-codes-25k.json:   0%|          | 0.00/26.4M [00:00<?, ?B/s]

python-codes-25k.jsonl:   0%|          | 0.00/25.4M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/49626 [00:00<?, ? examples/s]

Map:   0%|          | 0/993 [00:00<?, ? examples/s]

Map:   0%|          | 0/993 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

स्टेज 2 पूरा हुआ! मॉडल 'zeno_step2' में सेव हो रहा है...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

--- स्टेज 3 शुरू: राइटिंग और स्टोरीटेलिंग ---

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00004-2d5a1467fff108(…):   0%|          | 0.00/249M [00:00<?, ?B/s]

data/train-00001-of-00004-5852b56a2bd28f(…):   0%|          | 0.00/248M [00:00<?, ?B/s]

data/train-00002-of-00004-a26307300439e9(…):   0%|          | 0.00/246M [00:00<?, ?B/s]

data/train-00003-of-00004-d243063613e5a0(…):   0%|          | 0.00/248M [00:00<?, ?B/s]

data/validation-00000-of-00001-869c898b5(…):   0%|          | 0.00/9.99M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/2119719 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/21990 [00:00<?, ? examples/s]

Map:   0%|          | 0/42394 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

स्टेज 3 पूरा हुआ! फाइनल ZENO AI तैयार हो रहा है...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

🎉 बधाई हो! आपका स्टेप-बाय-स्टेप ट्रेन किया हुआ ZENO AI '/kaggle/working/zeno_final_model' में सेव हो गया है।

In [2]:
# 1. जरूरी लाइब्रेरीज (अगर पहले से रन नहीं हैं)
!pip install -q transformers datasets accelerate torch
import torch
import gc
import os
from datasets import load_dataset
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM, 
    Trainer, 
    TrainingArguments, 
    DataCollatorForLanguageModeling
)

print("🧠 ZENO AI का कंटीन्यूअस लर्निंग सिस्टम चालू हो रहा है...")

# ==========================================
# ⚙️ सेटिंग्स (यहाँ आप बदलाव कर सकते हैं)
# ==========================================

# पुराना मॉडल कहाँ रखा है? (इसे मत बदलें)
MODEL_PATH = "/kaggle/working/zeno_final_model"

# नया डेटासेट जो आप सिखाना चाहते हैं 
NEW_DATASET_NAME = "cfilt/iitb-english-hindi" 

# ==========================================

# 2. पुराना ZENO AI मॉडल और उसका दिमाग (Tokenizer) लोड करना
print("पुराना ज्ञान लोड किया जा रहा है ताकि कुछ भूले नहीं...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
tokenizer.pad_token = tokenizer.eos_token
model = AutoModelForCausalLM.from_pretrained(MODEL_PATH)

# 3. नया डेटासेट इंटरनेट से उठाना और फॉर्मेट करना
print(f"नया डेटा ({NEW_DATASET_NAME}) डाउनलोड हो रहा है...")
dataset = load_dataset(NEW_DATASET_NAME, split="train[:3%]") # 3% हिस्सा ले रहे हैं

# डेटा को सही फॉर्मेट में बदलने का फंक्शन (हिंदी-इंग्लिश के लिए)
def format_data(example):
    if 'translation' in example:
        en = example['translation'].get('en', '')
        hi = example['translation'].get('hi', '')
        return {"text": f"English: {en}\nHindi: {hi}"}
    elif 'text' in example:
        return {"text": example['text']}
    else:
        return {"text": str(example)}

formatted_dataset = dataset.map(format_data, remove_columns=dataset.column_names)

# 4. डेटा को मॉडल की भाषा में बदलना (Tokenization)
print("डेटा को मॉडल के समझने लायक बनाया जा रहा है...")
def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=128)

tokenized_dataset = formatted_dataset.map(tokenize_function, batched=True)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# 5. ट्रेनिंग की सेटिंग्स (FIXED)
args = TrainingArguments(
    output_dir="/kaggle/working/temp_update",
    num_train_epochs=1, 
    per_device_train_batch_size=4, # Memory (VRAM) बचाने के लिए इसे 8 से 4 कर दिया है
    save_strategy="no",            # ⚠️ FIX: बीच-बीच में सेव करना बंद कर दिया है ताकि Disk Space फुल न हो
    fp16=torch.cuda.is_available(), 
    report_to="none",
    learning_rate=2e-5 
)

trainer = Trainer(
    model=model, 
    args=args, 
    train_dataset=tokenized_dataset, 
    data_collator=data_collator
)

# 6. नई ट्रेनिंग शुरू!
print("🚀 नई ट्रेनिंग शुरू हो रही है...")
trainer.train()

# 7. अपडेटेड मॉडल को वापस उसी नाम से सेव करना
print("✅ ट्रेनिंग पूरी हुई! ZENO AI अब और भी ज्यादा स्मार्ट हो गया है। नया ज्ञान सेव किया जा रहा है...")

# सेव करने से पहले Kaggle का थोड़ा स्पेस खाली करें
import shutil
if os.path.exists("/kaggle/working/temp_update"):
    shutil.rmtree("/kaggle/working/temp_update")

model.save_pretrained(MODEL_PATH)
tokenizer.save_pretrained(MODEL_PATH)

# सिस्टम की मेमोरी साफ करना
del trainer, model, dataset, formatted_dataset, tokenized_dataset
torch.cuda.empty_cache()
gc.collect()

print("🎉 बधाई! ZENO AI का नया वर्ज़न तैयार है और सेव हो चुका है।")

🧠 ZENO AI का कंटीन्यूअस लर्निंग सिस्टम चालू हो रहा है...
पुराना ज्ञान लोड किया जा रहा है ताकि कुछ भूले नहीं...

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

नया डेटा (cfilt/iitb-english-hindi) डाउनलोड हो रहा है...

Map:   0%|          | 0/49772 [00:00<?, ? examples/s]

डेटा को मॉडल के समझने लायक बनाया जा रहा है...

Map:   0%|          | 0/49772 [00:00<?, ? examples/s]

🚀 नई ट्रेनिंग शुरू हो रही है...

✅ ट्रेनिंग पूरी हुई! ZENO AI अब और भी ज्यादा स्मार्ट हो गया है। नया ज्ञान सेव किया जा रहा है...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

🎉 बधाई! ZENO AI का नया वर्ज़न तैयार है और सेव हो चुका है।

In [3]:
# 1. Zaruri Libraries (अब लेटेस्ट वर्ज़न ही इस्तेमाल करेंगे)
!pip install -q transformers datasets accelerate torch
import torch, gc, os, shutil
from datasets import load_dataset, concatenate_datasets
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM, 
    Trainer, 
    TrainingArguments, 
    DataCollatorForLanguageModeling
)

print("🚀 ZENO AI: Engineering & Expert Coding Mode Activation...")

MODEL_PATH = "/kaggle/working/zeno_final_model"
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
tokenizer.pad_token = tokenizer.eos_token
model = AutoModelForCausalLM.from_pretrained(MODEL_PATH)

# ==========================================
# 📊 EXPERT DATASET LOADING (Parquet Supported)
# ==========================================

# A. Programming Knowledge (Modern Parquet Dataset)
print("1/2: Dunia bhar ki programming languages ka data load ho raha hai...")
# FIX: codeparrot की जगह एक मॉडर्न, Parquet-supported डेटासेट लगा दिया है
ds_pro_code = load_dataset("sahil2801/CodeAlpaca-20k", split="train[:5%]") 

def format_pro_code(example):
    return {"text": f"Task: {example.get('instruction', '')}\nCode:\n{example.get('output', '')}"}

ds_pro_code = ds_pro_code.map(format_pro_code, remove_columns=ds_pro_code.column_names)

# B. Advanced Engineering Mathematics
print("2/2: Engineering Mathematics aur Scientific Logic load ho raha hai...")
# FIX: trust_remote_code=True हटा दिया गया है क्योंकि यह डेटासेट अब सीधे सपोर्टेड है
ds_math = load_dataset("open-web-math/open-web-math", split="train[:1%]")

def format_math(example):
    return {"text": f"Mathematical Theory/Calculation: {example.get('text', '')}"}

ds_math = ds_math.map(format_math, remove_columns=ds_math.column_names)

# C. Mixing Both (Coding + Math)
expert_dataset = concatenate_datasets([ds_pro_code, ds_math]).shuffle(seed=42)

# ==========================================
# 🧠 TRAINING CONFIGURATION
# ==========================================

def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=256)

tokenized_dataset = expert_dataset.map(tokenize_function, batched=True)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Training Settings
args = TrainingArguments(
    output_dir="/kaggle/working/expert_temp",
    num_train_epochs=2, 
    per_device_train_batch_size=4, 
    gradient_accumulation_steps=4, 
    learning_rate=1e-5, 
    fp16=torch.cuda.is_available(),
    save_strategy="no", # Storage फुल होने से बचाने के लिए 
    report_to="none"
)

trainer = Trainer(
    model=model, 
    args=args, 
    train_dataset=tokenized_dataset, 
    data_collator=data_collator
)

# 🚀 Start Training
print("🛠️ ZENO AI ab ek Engineering Expert ban raha hai... Isme time lagega.")
trainer.train()

# Final save से पहले temp डेटा हटाना
if os.path.exists("/kaggle/working/expert_temp"):
    shutil.rmtree("/kaggle/working/expert_temp")

# Final Save
model.save_pretrained(MODEL_PATH)
tokenizer.save_pretrained(MODEL_PATH)

print("🎉 Mubarak Ho! ZENO AI ke paas ab coding aur math ka expert gyan hai.")

🚀 ZENO AI: Engineering & Expert Coding Mode Activation...

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

1/2: Dunia bhar ki programming languages ka data load ho raha hai...

README.md:   0%|          | 0.00/147 [00:00<?, ?B/s]

code_alpaca_20k.json: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/20022 [00:00<?, ? examples/s]

Map:   0%|          | 0/1001 [00:00<?, ? examples/s]

2/2: Engineering Mathematics aur Scientific Logic load ho raha hai...

README.md: 0.00B [00:00, ?B/s]

Resolving data files:   0%|          | 0/114 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/114 [00:00<?, ?files/s]

data/train-00000-of-00114-5a023365406cb9(…):   0%|          | 0.00/236M [00:00<?, ?B/s]

data/train-00001-of-00114-e32fc2813a15f6(…):   0%|          | 0.00/238M [00:00<?, ?B/s]

data/train-00002-of-00114-1429d96b99aec5(…):   0%|          | 0.00/238M [00:00<?, ?B/s]

data/train-00003-of-00114-e7fc257ef044bc(…):   0%|          | 0.00/242M [00:00<?, ?B/s]

data/train-00004-of-00114-3158c787ea8296(…):   0%|          | 0.00/237M [00:00<?, ?B/s]

data/train-00005-of-00114-c525c7efee4422(…):   0%|          | 0.00/245M [00:00<?, ?B/s]

data/train-00006-of-00114-c82ec070af45d2(…):   0%|          | 0.00/240M [00:00<?, ?B/s]

data/train-00007-of-00114-36c74b525c9694(…):   0%|          | 0.00/242M [00:00<?, ?B/s]

data/train-00008-of-00114-bf41cf8843148a(…):   0%|          | 0.00/245M [00:00<?, ?B/s]

data/train-00009-of-00114-691ac94b115fea(…):   0%|          | 0.00/244M [00:00<?, ?B/s]

data/train-00010-of-00114-5805e25b488496(…):   0%|          | 0.00/236M [00:00<?, ?B/s]

data/train-00011-of-00114-da8ee2fcf07be1(…):   0%|          | 0.00/243M [00:00<?, ?B/s]

data/train-00012-of-00114-7252b11ca4b39a(…):   0%|          | 0.00/237M [00:00<?, ?B/s]

data/train-00013-of-00114-a189dcaf5ac68c(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00014-of-00114-23a118ee3aaea5(…):   0%|          | 0.00/242M [00:00<?, ?B/s]

data/train-00015-of-00114-e65817847eac68(…):   0%|          | 0.00/235M [00:00<?, ?B/s]

data/train-00016-of-00114-7b0ca70e75bb60(…):   0%|          | 0.00/243M [00:00<?, ?B/s]

data/train-00017-of-00114-7680a1785b342d(…):   0%|          | 0.00/236M [00:00<?, ?B/s]

data/train-00018-of-00114-f187dd9c797b31(…):   0%|          | 0.00/245M [00:00<?, ?B/s]

data/train-00019-of-00114-95e7ebe4402c9b(…):   0%|          | 0.00/243M [00:00<?, ?B/s]

data/train-00020-of-00114-49f2b2f31d3488(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00021-of-00114-64c103f9fbdf2c(…):   0%|          | 0.00/238M [00:00<?, ?B/s]

data/train-00022-of-00114-4d18242ef5fd31(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00023-of-00114-9ec2a6a02bf1d9(…):   0%|          | 0.00/237M [00:00<?, ?B/s]

data/train-00024-of-00114-92f9f033a294f3(…):   0%|          | 0.00/243M [00:00<?, ?B/s]

data/train-00025-of-00114-f8488d391fad90(…):   0%|          | 0.00/237M [00:00<?, ?B/s]

data/train-00026-of-00114-895ba22c761501(…):   0%|          | 0.00/243M [00:00<?, ?B/s]

data/train-00027-of-00114-97a6e351f6fc32(…):   0%|          | 0.00/242M [00:00<?, ?B/s]

data/train-00028-of-00114-0d11fc4f464d6d(…):   0%|          | 0.00/242M [00:00<?, ?B/s]

data/train-00029-of-00114-5c297df81e0ef9(…):   0%|          | 0.00/240M [00:00<?, ?B/s]

data/train-00030-of-00114-890f9615f1b857(…):   0%|          | 0.00/236M [00:00<?, ?B/s]

data/train-00031-of-00114-d06b98184be0a9(…):   0%|          | 0.00/245M [00:00<?, ?B/s]

data/train-00032-of-00114-4fee32b54661f2(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00033-of-00114-d20028bef60057(…):   0%|          | 0.00/238M [00:00<?, ?B/s]

data/train-00034-of-00114-627b0a1638e867(…):   0%|          | 0.00/242M [00:00<?, ?B/s]

data/train-00035-of-00114-5c1b8e81c0be03(…):   0%|          | 0.00/239M [00:00<?, ?B/s]

data/train-00036-of-00114-b346e68b971d34(…):   0%|          | 0.00/245M [00:00<?, ?B/s]

data/train-00037-of-00114-18f228cb81d4f3(…):   0%|          | 0.00/243M [00:00<?, ?B/s]

data/train-00038-of-00114-59d446a886db42(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00039-of-00114-7eb5d8ce001f35(…):   0%|          | 0.00/237M [00:00<?, ?B/s]

data/train-00040-of-00114-67f9d4881b81ae(…):   0%|          | 0.00/240M [00:00<?, ?B/s]

data/train-00041-of-00114-c6d5c710a54b71(…):   0%|          | 0.00/244M [00:00<?, ?B/s]

data/train-00042-of-00114-ae04fe2a9c8302(…):   0%|          | 0.00/243M [00:00<?, ?B/s]

data/train-00043-of-00114-2313cb610d98e9(…):   0%|          | 0.00/238M [00:00<?, ?B/s]

data/train-00044-of-00114-45624487e9a412(…):   0%|          | 0.00/237M [00:00<?, ?B/s]

data/train-00045-of-00114-dae3a4ce38fbb8(…):   0%|          | 0.00/237M [00:00<?, ?B/s]

data/train-00046-of-00114-aae2216d332a8b(…):   0%|          | 0.00/235M [00:00<?, ?B/s]

data/train-00047-of-00114-c530007ea6bb7e(…):   0%|          | 0.00/239M [00:00<?, ?B/s]

data/train-00048-of-00114-adbd9ee1526b2f(…):   0%|          | 0.00/240M [00:00<?, ?B/s]

data/train-00049-of-00114-4fefd2e02ac88e(…):   0%|          | 0.00/239M [00:00<?, ?B/s]

data/train-00050-of-00114-641de5515646eb(…):   0%|          | 0.00/240M [00:00<?, ?B/s]

data/train-00051-of-00114-4e33803d640645(…):   0%|          | 0.00/246M [00:00<?, ?B/s]

data/train-00052-of-00114-19ab8807098890(…):   0%|          | 0.00/238M [00:00<?, ?B/s]

data/train-00053-of-00114-97447325975763(…):   0%|          | 0.00/239M [00:00<?, ?B/s]

data/train-00054-of-00114-84e7f6d0ab717c(…):   0%|          | 0.00/237M [00:00<?, ?B/s]

data/train-00055-of-00114-01e9c7d6d954e9(…):   0%|          | 0.00/240M [00:00<?, ?B/s]

data/train-00056-of-00114-78b64b52f016ba(…):   0%|          | 0.00/239M [00:00<?, ?B/s]

data/train-00057-of-00114-f45202cfdbcd28(…):   0%|          | 0.00/240M [00:00<?, ?B/s]

data/train-00058-of-00114-bf8a0e1e48110a(…):   0%|          | 0.00/239M [00:00<?, ?B/s]

data/train-00059-of-00114-b500637ee2ebb2(…):   0%|          | 0.00/239M [00:00<?, ?B/s]

data/train-00060-of-00114-74ce66249e0d84(…):   0%|          | 0.00/246M [00:00<?, ?B/s]

data/train-00061-of-00114-d55caeba8fd91a(…):   0%|          | 0.00/244M [00:00<?, ?B/s]

data/train-00062-of-00114-7ee2ae42584823(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00063-of-00114-7455c94d26bc43(…):   0%|          | 0.00/240M [00:00<?, ?B/s]

data/train-00064-of-00114-a54c530c88d036(…):   0%|          | 0.00/239M [00:00<?, ?B/s]

data/train-00065-of-00114-9d2d2227194ee9(…):   0%|          | 0.00/244M [00:00<?, ?B/s]

data/train-00066-of-00114-111c17033ab8bd(…):   0%|          | 0.00/244M [00:00<?, ?B/s]

data/train-00067-of-00114-00b0cfdec58c88(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00068-of-00114-f8df664e88faba(…):   0%|          | 0.00/237M [00:00<?, ?B/s]

data/train-00069-of-00114-3d5279cf4c88ec(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00070-of-00114-00d409298080d3(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00071-of-00114-9b92b6565dc971(…):   0%|          | 0.00/240M [00:00<?, ?B/s]

data/train-00072-of-00114-59c4ddad7738c3(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00073-of-00114-daa3ea18691223(…):   0%|          | 0.00/239M [00:00<?, ?B/s]

data/train-00074-of-00114-b9ba5eaf8a91ad(…):   0%|          | 0.00/242M [00:00<?, ?B/s]

data/train-00075-of-00114-918d14857d807f(…):   0%|          | 0.00/240M [00:00<?, ?B/s]

data/train-00076-of-00114-4abc935890da0f(…):   0%|          | 0.00/239M [00:00<?, ?B/s]

data/train-00077-of-00114-82832e79c319ea(…):   0%|          | 0.00/240M [00:00<?, ?B/s]

data/train-00078-of-00114-fad2b3b99f01b9(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00079-of-00114-1e830c9406ba82(…):   0%|          | 0.00/242M [00:00<?, ?B/s]

data/train-00080-of-00114-7e0742992331e6(…):   0%|          | 0.00/243M [00:00<?, ?B/s]

data/train-00081-of-00114-7687eb97c0e83e(…):   0%|          | 0.00/239M [00:00<?, ?B/s]

data/train-00082-of-00114-5f74aaa3f0e5e2(…):   0%|          | 0.00/243M [00:00<?, ?B/s]

data/train-00083-of-00114-42a01c2d531e71(…):   0%|          | 0.00/237M [00:00<?, ?B/s]

data/train-00084-of-00114-77bf15a870bfc6(…):   0%|          | 0.00/243M [00:00<?, ?B/s]

data/train-00085-of-00114-8d3357e0c795d8(…):   0%|          | 0.00/238M [00:00<?, ?B/s]

data/train-00086-of-00114-8801fbceef8a17(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00087-of-00114-c00ab7c9d82d46(…):   0%|          | 0.00/239M [00:00<?, ?B/s]

data/train-00088-of-00114-21dc7966e8cf32(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00089-of-00114-6bed8732922b7f(…):   0%|          | 0.00/242M [00:00<?, ?B/s]

data/train-00090-of-00114-81a5f980ee29b1(…):   0%|          | 0.00/238M [00:00<?, ?B/s]

data/train-00091-of-00114-8f1b9b8cb25b9b(…):   0%|          | 0.00/240M [00:00<?, ?B/s]

data/train-00092-of-00114-0dbff189ab3417(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00093-of-00114-8277bc96af3263(…):   0%|          | 0.00/239M [00:00<?, ?B/s]

data/train-00094-of-00114-baedcd5a73cc7d(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00095-of-00114-6e5bde2b7ac4ae(…):   0%|          | 0.00/242M [00:00<?, ?B/s]

data/train-00096-of-00114-1c45362bad7ef7(…):   0%|          | 0.00/242M [00:00<?, ?B/s]

data/train-00097-of-00114-933ac1d225e072(…):   0%|          | 0.00/237M [00:00<?, ?B/s]

data/train-00098-of-00114-526e74a33c317a(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00099-of-00114-c587048e642b13(…):   0%|          | 0.00/243M [00:00<?, ?B/s]

data/train-00100-of-00114-756242e207ced0(…):   0%|          | 0.00/245M [00:00<?, ?B/s]

data/train-00101-of-00114-312d73b894e70a(…):   0%|          | 0.00/238M [00:00<?, ?B/s]

data/train-00102-of-00114-cc1e36c47fea80(…):   0%|          | 0.00/243M [00:00<?, ?B/s]

data/train-00103-of-00114-84c1737cd95390(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00104-of-00114-f8032e7edb2aed(…):   0%|          | 0.00/239M [00:00<?, ?B/s]

data/train-00105-of-00114-880aef5103d3d4(…):   0%|          | 0.00/241M [00:00<?, ?B/s]

data/train-00106-of-00114-dee47fa03a21ac(…):   0%|          | 0.00/239M [00:00<?, ?B/s]

data/train-00107-of-00114-0356b6d64e39bc(…):   0%|          | 0.00/246M [00:00<?, ?B/s]

data/train-00108-of-00114-b910fc59043684(…):   0%|          | 0.00/245M [00:00<?, ?B/s]

data/train-00109-of-00114-0b4af773d9477c(…):   0%|          | 0.00/245M [00:00<?, ?B/s]

data/train-00110-of-00114-f2afd5ad965480(…):   0%|          | 0.00/245M [00:00<?, ?B/s]

data/train-00111-of-00114-72f184ecf01de3(…):   0%|          | 0.00/243M [00:00<?, ?B/s]

data/train-00112-of-00114-5fdaac128cc9da(…):   0%|          | 0.00/244M [00:00<?, ?B/s]

data/train-00113-of-00114-c2949ce8a6072e(…):   0%|          | 0.00/235M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/6315233 [00:00<?, ? examples/s]

Map:   0%|          | 0/63152 [00:00<?, ? examples/s]

Map:   0%|          | 0/64153 [00:00<?, ? examples/s]

🛠️ ZENO AI ab ek Engineering Expert ban raha hai... Isme time lagega.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

🎉 Mubarak Ho! ZENO AI ke paas ab coding aur math ka expert gyan hai.